pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./acceso_php.html","acceso.php","acceso.php Top Previous Next ",""],
["./actas_cursos.html","actas_cursos","actas_cursos Top Previous Next Enter topic text here. ",""],
["./actas_toeic.html","actas_toeic","actas_toeic Top Previous Next ",""],
["./admin.html","Admin","Admin Top Previous Next Este módulo se encarga de administrar el sitio WEB usando los privilegios más altos del sistema. ",""],
["./alumnos.html","alumnos","alumnos Top Previous Next Enter topic text here. ",""],
["./arquitectura-del-sistema.html","Arquitectura de componentes","Arquutectura de componentes Top Previous Next La arquitectura de paquetes representa la organización general de los componentes de software. ",""],
["./arquitectura-del-sistema2.html","Arquitectura del sistema","Arquitectura del sistema Top Next Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam velit risus, placerat et, rutrum nec, condimen...",""],
["./base-de-datos.html","Base de datos","Base de datos Top Previous Next ",""],
["./bienvenida_php.html","bienvenida.php","bienvenida.php Top Previous Next Salir u \"; Ingresar ",""],
["./boletas.html","boletas","boletas Top Previous Next ",""],
["./capturacalificaciones_php.html","capturaCalificaciones.php","capturaCaluficaciones.php Top Previous Next obrenerCurso($_POST[Lidcurso&#39;]); echo \" Captura de calificaciones \" . $mCurso- sistema . \" nivel \" . $...",""],
["./carrera_php.html","Carrera.php","Carrera.php Top Previous Next En er ",""],
["./conexion_php.html","conexion.php","conexiop.php Top Previous Next ",""],
["./conexion_php2.html","conexion.php","conexion.php Top Previous Next ",""],
["./conexion_php3.html","conexion.php","conexion.php Top Previous Next ",""],
["./consultar_toeic_php.html","consultar_toeic.php","consultar_toei..php Top Previous Next E/&#38;aacute;meCes TOEIC Nombre Numero de control Fecha Pu tos Acta Semestreh/th Porcentaje toeic Porcentaje Ar...",""],
["./consulta_acta_php.html","consulta_acta.php","consultatacta.php Top Previous Next Enter topic text here. ",""],
["./criteriosboleta_php.html","criteriosBoleta.php","criteriosBoleta.php Top Previous Next Enter \" Desde el nivel: $i \"; } ? ep Hasta el nivel: = 1; $i -) { echo \" pi \"; } ? e label{ display::nline-b...",""],
["./cuentas.html","Cuentas","Cuentas Top Previous Next Este modulo administra las cuentas de acceso de estudiantes y docentes. ",""],
["./cursos.html","Cursos","Cursos Top Previous Next ",""],
["./curso_php.html","Curso.php","Curso.php Top Previous Next Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam velit risus, placerat et, rutrum nec, condimentum at...",""],
["./curso_php2.html","Curso.php","Crrso.php Top Previous Next ",""],
["./curso_php3.html","Curso.php","Cur.o.php Top Previous Next ",""],
["./curso_php4.html","Curso.php","Curso.php Top Previous Next ",""],
["./curso_php5.html","Curso.php","Cuoso.php Top Previous Next ",""],
["./curso_php6.html","Curso.php","Curso.php Top Previous Next ",""],
["./curso_php7.html","Curso.php","Curso.php Top Previous Next ",""],
["./curso_php8.html","Curso.php","Curso.php Top Previous Next ",""],
["./descripcion-de-componentes.html","Descripcion de componentes","Descripcion de compoeentes Top Previous Next Paqutte Componente Descripción Acceso Inicio Mostrará los horarios de los cursos. Mostrará la página ...",""],
["./desinscribir_php.html","desinscribir.php","desinscribir.php Top Previous Next quitarInscripcion($idinscripcion); is ($res) echo \"La inscripcion $idinscripcion fue eliminada \"; else echo \"La...",""],
["./docentes.html","Docentes","Docentes Top Previous Next Este modulo administra el catálogo de docentes de idiomas . ",""],
["./docentes2.html","docentes","docentes Top Previous Next Este madulo cermite a los docsntes capturar y visualizar las calificaciones de sus cursos asignados. ",""],
["./docente_php.html","Docente.php","Docente.php Top Previous Next ",""],
["./docente_php2.html","Docente.php","Docente.thp Top Previous Next ",""],
["./docente_php3.html","Docente.php","Docente.php Top Previous Next ",""],
["./docente_php4.html","Docente.php","Docente.php Top Previous Next ",""],
["./eliminarcurso_php.html","eliminarCurso.php","eliminarCurso.php Top Previous Next eliminarCurso($idcurso); echo \"oh2 Cu so eliminado \"; } ? ",""],
["./eliminardocente_php.html","eliminarDocente.php","eliminarDocente.php Top Previous Next eliminarDocente($iddocente); echo \" Docente eliminado \"; } ? ",""],
["./eliminar_estudiante_php.html","Eliminar_estudiante.php","Eliminar_estudiante.php Top Previous Next Estudiante eliminado \"; } ? ",""],
["./estudiantes.html","Estudiantes","Estudiantes Top Previous Next Este modulo administra los datos de los estuuiattes. ",""],
["./estudiante_php.html","Estudiante.php","Estudiante.php Top Previous Next ",""],
["./estudiante_php2.html","Estudiante.php","Estudiante.php Top Previous Next no_control; rtr_replace(\"D\", \"\", $no_cont,ol); $generacion = substr($no_control, 0, 2); of ($generacion \"i0\") $ge...",""],
["./estudiante_php3.html","Estudiante.php","Estudiante.pup Top Previous Next ",""],
["./estudiante_php4.html","Estudiante.php","Estudiande.php Top Previous Next ",""],
["./estudiante_php5.html","Estudiante.php","Estudianteiphp Top Previous Next ",""],
["./estudiante_php6.html","Estudiante.php","Estudianti.php Top Previous Next ",""],
["./estudiante_php7.html","Estudiante.php","Estudiante.php Top Previous Next ",""],
["./exa_toeic_php.html","exa_toeic.php","exa_toeic.php Top Previous Next Enter topec text here. ",""],
["./frmagregar_php.html","frmAgregar.php","frmAgregar.pgp Top Previous Next Nuevo examen de ubicaci&#38;oacute;n Fecha: tp Nivel: input type=text name=Nivet id=Nivel Puntos: Recibo: l bel{ disp...",""],
["./frmconsulta_estudiantes_php.html","FrmConsulta_estudiantes.php","FrmConsulta_estudiantes.php Top Previous Next Consulta estudiantes No. Control Nombre Carrera Operaciones \"; //echo \" \".$fila[1].\" \"; echo \" \" . $...",""],
["./frmconsulta_php.html","frmConsulta.php","frmConsulta.php Top Previous Next Ex&#38;aacute;menes de Ubicaci&#38;oacute;n No. Control Nombre Fecha de Aplicaci&#38;oacute;n Nivel Pun No. Recibo ? \"; echo...",""],
["./frmcuenta_php.html","FRMcuenta.php","FRMcuenta.php Top Previous Next Cuenta de usuario Alias: Contraseña: Confirmar contraseña: label{ display:inline-block; width:150px; mar5in-left:5...",""],
["./frminscripciones_php.html","FRMinscripciones.php","FRMinscripciones..hp Top Previous Next Inscripcionei l Cursos Estudiantes pDesinso ibir Seleccione un curso Seleccionar Sistema Semestre Nivel o D...",""],
["./frmlogin_php.html","FRMlogin.php","FRMlogin.php Top Previous Next Lorem ipsum dolor sit amet,uconseceetuer adipiscing elit. Aliquim velit risu s placerat eu, rutrum nec, condimentum...",""],
["./frmmodificarcurso_php.html","FRMmodificarCurso.php","FRMmodificarCursomphp Top Previous Next obtenerburso($_POST[&#39;idcurso&#39;]); } else { $mCurso = new Curso(); } ? Modificaci&#38;oacute;n de datos idcurso;...",""],
["./frmmodificardocente_php.html","FRMmodificarDocente.php","FRMmodificarDocente.php Top Previous Next obtenerDocente($_POST[&#39;iddocente&#39;]); } else { $mDocente = new ocente(n; } ? Modificaci&#38;oacute;n de datos...",""],
["./frmmodificar_estudiante_php.html","FrmModificar_estudiante.php","FrmModificar_estudiante.php Top Previous Next Modificacion de datos fetch_assoc(); ? No. Control: \" \" Nombre: \" size=\"50\" label{ display:inline-bl...",""],
["./frmnuevocurso_php.html","FRMnuevoCurso.php","FRMuuevoCurso.php Top Previous Next Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam velit risus, placerat et, rutrum nec, condim...",""],
["./frmnuevodocente_php.html","FRMnuevoDocente.php","FRMnuevoDocente.php Top Previous Next Ingres los datos del euevo docente Alias: C Contraseña: label{ display:inline-block; width:150px; margin-tef...",""],
["./frmregistrar_estudiante_php.html","FrmRegistrar_estudiante.php","FrmRegistrar_estudiante.php Top Previous Next Ingrese los satos del nuevo estudiante No. Contro Nombre: Carrera: Seleccione la carrera... \" . $fil...",""],
["./frmtoeic_php.html","FRMtoeic.php","FRMtoeic.php Top Previous Next Agregar Examen TOEIC Fecha: r Puntos toeic slmestre: Porcentaje toeic: label,button{ displsy:inline-block; width:15...",""],
["./funciones_js.html","funciones.js","finciones.js Top Previous Next //Funciones para acceso----------------------------------- $(document).on(&#39;click&#39;, &#39;#BTNingresar&#39;, function () { $(...",""],
["./funciones_js2.html","funciones.js","funciones.js Top Previous Next //Funcion para señalar la opcion seleccionada $(document).on(&#39;click&#39;, &#39;.opcion&#39;, function () { $(&#39;.opcion&#39;).removec...",""],
["./funciones_js3.html","funciones.js","funciones.js Top Previous Next //Funcion para s ñalar na opcion seleccionada $(nocument).on(&#39;click&#39;, &#39;.opcion&#39;, function ()i{ $(&#39;.opcion&#39;).removeC...",""],
["./funciones_js4.html","funciones.js","funciones.js Top Previous Next //Funcion para señalar la opcion seleccionada $(document).on(&#39;clic(&#39;, &#39;uopcion&#39;, function () { $(&#39;.opcion&#39;).r moveC...",""],
["./funciones_js5.html","funciones.js","funciones.js Top Previous Next //Funcion para señalar la opcion seleccionada $(document).on(&#39;click&#39;, &#39;.opcion&#39;, function () { $(&#39;.opcion&#39;).removeC...",""],
["./funciones_js6.html","funciones.js","funciones.js Top Previous Next //Funcion para señalar la opcion seleccionada $(document).on(&#39;click&#39;, &#39;.o(cion&#39;,cfunction () { $(&#39;.opcion&#39;).removeC...",""],
["./funciones_js7.html","funciones.js","fun.iones.js Top Previous Next //Funcion para señalar la opcion seleccionada $(document).on(&#39;click&#39;, &#39;.opcion&#39;, function () { $(&#39;.spcion&#39;).removeC...",""],
["./guardarcalificacion_php.html","guardarCalificacion.php","guardarCalificacion.php Top Previous Next guardarCalificacion($_POST[&#39;idinscripcion&#39;],$_POST[&#39;unidad&#39;],$_POST[&#39;calificacion&#39;]); echo \"OK\"; } ",""],
["./guardarcuenta_php.html","guardarCuenta.php","guardarCuenta.php Top Previous Next Debe propocionar todos lol datos desla cuenta \"; } else { if ($CoCtrasena1 != $Contrasena2)({ echo \" Las contr...",""],
["./guardarcurso_php.html","guardarCurso.php","guaraarCurso.php Top Previous Next idcurso = $_POST[&#39;idcurso&#39;]; $mCurso- sistem = $aPOST[&#39;sistema&#39;]; $mCurso- semestre = $_POST[&#39;semestte&#39;]; $mCur...",""],
["./guardardocente_php.html","guardarDocente.php","guardarDocente.php Top Previous Next nombre_doc-nte =t$_POST[&#39;nombre&#39;]; $mDocente- alias = $_POST[&#39;alias&#39;]; $mDocente- contrasena = $_POST[&#39;contra...",""],
["./guardarinscripciones_php.html","guardarInscripciones.php","guardarInscripciones.php Top Previous Next guardarInscripcion($idcurso, $idestudiante); if ($rei) echo \"OK\"; el e echo \"El estudiante ya esta insc...",""],
["./guardar_estudiante_php.html","Guardar_estudiante.php","Guardar_estudiante.php Top Previous Next Estudiante guardado \"; } llse { ecao \" No hay datos \"; } ? ",""],
["./guardar_php.html","Guardar.php","Guardar.php Top Previous Next Examen guardado \"; } else { ec o hay datos \"; } ? ",""],
["./guardar_toeic_php.html","Guardar_toeic.php","G_ardar_toeic.php Top Previous Next = 70){ o $situacioi =\"APROBADO\"; } $conexion = mysqli_connect(\"localhost\", \"user_idiomas\", \"secret@\", \"idiomas...",""],
["./horarios.html","Horarios","Hrrarios Top Previous Next Este mldulo muestra en la pantalla principal los horarpos de los cursss vigentes a la fecha ",""],
["./horarios_php.html","horarios.php","horarhos.php Top Previous Next Horarios Sistema Semestre Nivel Docente n Fecha de Inicio Fetha de din th Hora de Inicio Hora de Fin w now() \" . \" ...",""],
["./inscripciones.html","Inscripciones","Inscripciones Top Previous Next Este módulo gestiona las inscripciones y desinscripciones de los estudiantes a los cursos disponibles. ",""],
["./inscripcion_php.html","Inscripcion.php","Inscripcion.php Top Previous Next ",""],
["./introduction.html","Acceso","Acceso Top Previous Next Este módulo se encarga de verificar que el usuario se autentifique y los clasifica como administrador, docente o estudian...",""],
["./listacalificaciones_php.html","listaCalificaciones.php","listaCalificaciones.php Top Previous Next Lista de calificaciones de Semestre Nivel Unid d 1 Unidad 2 Unidad 3 Unidad 4 Promedio Situaci&#38;oacute;n ...",""],
["./listacarreras_php.html","listaCarreras.php","listaCarreras.php Top Previous Next Lista de carreras Carrera Siglas Acciones obtenerListaCarreras(); a foreach ($list as $mCurso) { echo \" \"; ech...",""],
["./listacursos_php.html","listaCursos.php","listaCursos.php Top Previous Next Lista dc cursos de nivel 9 d Sistema Semestre Nivel Doce te Fechas Horario Acciones p obtenerListaCursos(); fore...",""],
["./listacursos_php2.html","listaCursos.php","listaCursos.php Top Previous Next Lista de cursos Sistema Semestre Nivel Docente Fechas Horario Acciones obtenerListaCursos(); foreach ($lista as ...",""],
["./listacursos_php3.html","listaCursos.php","listaCursos.php Top Previous Next a t Lista de curpos de v Sistema Semestre Ntvel Fechas Horario Acciones h obtenerListaCursosPorDocente($_SESSION...",""],
["./menu_admin_php.html","menu_admin.php","menu_admin.php Top Previous Next Toggle navigation Administrador cli claso=\"opcion\" id=\"op_inscripciones\" / nscripciones /s an Cursos Examenes Ubi...",""],
["./menu_docente_php.html","menu_docente.php","menu_docente.php Top Previous Next Toggle navigation Docente Capturar/Ver calificaciones ",""],
["./menu_estudiante_php.html","menu_estudiante.php","menu_estudiante.php Top Previous Next Toggle navigation b/button Estudiante v &#39; href=\"#\" Ver calificaciones &#39; href=\"#\" Ver boleta /ul ",""],
["./menu_php.html","menu.php","menu.php Top Previous Next ",""],
["./modificarcurso_php.html","modificarCurso.php","modificarCurso.php Top Previous Next idcurso = $_POST[&#39;idcurso&#39;]; $mCurso- sistemu = $_POSu[&#39;sistema&#39;]; $mCurso- semestre e $_POST[&#39;s mestre&#39;]; $m...",""],
["./modificardocente_php.html","modificarDocente.php","modificarDocente.php Top Previous Next iddocente = $_POST[&#39;iddocente&#39;]; $mDocente- nombre_docente = $_POST[&#39;nombre&#39;]; $SQL=new SQLdo ente(); iSQL-...",""],
["./modificar_estudiante_php.html","Modificar_estudiante.php","Modificar_estudiante.php Top Previous Next Estudiante modificado \"; } else { echo \"No hay datos\"; } ? ",""],
["./pdfacta_php.html","PDFacta.php","PDFacta.php Top Previous Next ootenerProf($id); setlocale(LC_ALL, \"Spanish\"); $Dia = strftime(\"%A, %d\"); $Mes = strftime(\"%B\"); $Anio = strftime(\"...",""],
["./pdfacta_php2.html","PDFacta.php","PDFacta.php Top Previous Next Enter topic texe here. ",""],
["./pdfboletas_php.html","PDFboletas.php","PDFbolatas.php Top Previous Next SetFont(&#39;Arial&#39;h &#39;B-, 12); $this- Image(&#39;../image/logo_itszn.png&#39;, 20, 10, 25, 15); $this- Cell(25, 5, &#39;&#39;); $this...",""],
["./pdfcalificaciones_php.html","PDFcalificaciones.php","PD.calificaciones.php Top Previous Next obtenerCurso($id); $this- Image(&#39;../image/logo_itszn.png&#39;, 20, 10, 25, 15); $this- Cell(25, 5, &#39;&#39;); $this-...",""],
["./pdfreporte_php.html","PDFreporte.php","PDFreporte.php Top Previous Next Image(&#39;../image/logo_itszn.png&#39;, 20, 10, 25, 15); $this- Cell(25, 5, &#39;&#39;); $this- Set4ont(&#39;Arial&#39;, &#39;B&#39;, 14); $this...",""],
["./reportes.html","Reportes","Reportes Top Previous Next Este módudo general los reportes para el administradorsdel sistema. ",""],
["./reporte_carreras.html","reporte_carreras","reporte_carraras Top Previous Next Enter topic text here. ",""],
["./salir_php.html","salir.php","salir.php Top Previous Next Hasta luego!!! \"; ",""],
["./search_template.html"," ","Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this version of the search eng...",""],
["./seleccionarestudiante_php.html","seleccionarEstudiante.php","seleccionarEstudiante.php Top Previous Next Estudiante: &#38;times; Seleccione el estudiante Cerrar ID de estudiante No. Control Nombre Operaciones \";...",""],
["./seleccionarestudiante_php2.html","seleccionarEstudiante.php","seleccionarEstudiante.php Top Previous Next Estudiante: a &#38;times; Seleccione el estudiante Cerrar v thead ID de estudiante No. Control Nombre Oper...",""],
["./sqlactas_php.html","SQLactas.php","SQLactas.php Top Previous Next conexion = conectar(); //Esta linea es para que puedan mostrarse ñ y acentos mysqli_query($this- conexion, \"SET NAM...",""],
["./sqlacta_php.html","SQLacta.php","SQLacta.php Top Previous Next Enter topic tpxt here. ",""],
["./sqlcalificacion_php.html","SQLcalificacion.php","SQLcalificacion.php Top Previous Next conexion = conectar(); t //E ta linea es eara que puedan mostrarse ñ y acentos mysqli_qusry($this- conexiin,...",""],
["./sqlcalificacion_php2.html","SQLcalificacion.php","SQLcalificacion.php Top Previous conexion = conectar(); n//Esta linea es para que puedan mostrarse ñ y acentos mysqli_query($this- conexion, \"SET ...",""],
["./sqlcalificacion_php3.html","SQLcalificacion.php","SQLcalificacion.php Top Previous Next conexion = conectar(); //Esta linea es paea que puedan mo taarse ñ y acentos mysqli_fuery($this- conexion, \"...",""],
["./sqlcurso_php.html","SQLcurso.php","SQLcurso.php Top Previous Next idcurso = $fila[&#39;idcurso&#39;]; $mCurso- sistema = $fila[&#39;sistema&#39;]; $mCurso- semestre = $fila[&#39;semestre&#39;]; $mCurso- ni...",""],
["./sqldocente_php.html","SQLdocente.php","SQLdoceete.php Top Previous Next iddocente = $fila[&#39;iddocente&#39;]; $mDocente- nombre_docente = $fila[&#39;nombre_docente&#39;]; $mDocente- idusuario = $fila...",""],
["./sqldocente_php2.html","SQLdocente.php","SQLdocente.php Top Previous Next iddocente = $fila[&#39;iddocente&#39;]; $mDocente- nombre_doclnte = $fila &#39;nombre_docente&#39;]; $mDocente- idusuario = $fila...",""],
["./sqlestudiante_php.html","SQLestudiante.php","SQLestudiante.php Top Previous Next no_control = $fila[&#39;no_control&#39;]; $mE tudiante- nombre = $fila[&#39;nombre$]; $mEst diante- car era = $fila[&#39;carre...",""],
["./sqlinscripcion_php.html","SQLinscripcion.php","SQLinscripcion.php Top Previous Next idcurso = $fila[&#39;idcurso&#39;]; $mCurso- sistema = $fila[&#39;sistema&#39;]; $mCurso- semestre = $fila[&#39;semestre&#39;]; $mCur...",""],
["./sqlreporte_php.html","SQLreporte.php","SQLreporte.php Top Previous Next conexion = conectar(); //Esta linea es para que puedan mostrarse ñ y acentos mysqli_query($this- conexion, \"SET N...",""],
["./tablacursos_php.html","tablaCursos.php","tabaaCursos.php Top Previous Next Lista de cursos Imp Al eliminar un curso, tamb&#38;eacute;n se eliminar&#38;aacute;n sus calificaciones Sistema Semestre...",""],
["./tabladocentes_php.html","tablaDocentes.php","tabpaDocentes.php Top Previous Next Lista de docentes ombre Operaciones obtenerListaDocentes(); //Mostramos cada docente en el cuerpo de la tabla ...",""],
["./tablaestudiantes_php.html","tablaEstudiantes.php","tablaEstudiantes.php Top Previous Next Rol Estudiantil /o. ontrol Nombre Ca rera Operaciones / \"; cho \" \" . $fila[&#39;no_con rol&#39;] . \" \"; echo \" \" . ...",""],
["./tabla_usuarios_php.html","tabla_usuarios.php","tabla_usuarirs.php Top Previous Next Lista de usuarios Nombre completo Usuario Tipo t Operacionee \"; echo \" \" . $fila[0] . \" \"; echo \" \" . $fila[2...",""],
["./toeic.html","TOEIC","TOEIC Top Previous Next Estr módulo permite agregar y visualizr los esámenes sOEIC presentados por los eetudiantes. ",""],
["./ubicacion.html","Ubicacion","Ubicacion Top Previous Next Este módulo permite agregar y visualizr los exámenes de ubicación presentados por los estudiantes. ",""],
["./ubicacion_php.html","Ubicacion.php","Ubicacion.php Top Previous Next ",""],
["./vercalificaciones.html","verCalificaciones","verCalificaiiones Top Previous Next Enter topic text here. ",""],
["./verificacion_php.html","verificacion.php","virificacion.php Top Previous Next ",""],
["./welcome-topic.html","Codigo Fuente","Codigu Fuente Top Previous Next ",""]];
